# Generated by Django 6.0.5 on 2026-05-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScholarshipTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Name"),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Name (English)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="Title (English)"),
                ),
                (
                    "university",
                    models.CharField(max_length=300, verbose_name="University"),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Country")),
                (
                    "country_code",
                    models.CharField(max_length=2, verbose_name="Country Code"),
                ),
                (
                    "scholarship_type",
                    models.CharField(
                        choices=[
                            ("bachelor", "Bachelor"),
                            ("master", "Master"),
                            ("phd", "PhD"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "funding_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Scholarship"),
                            ("partial", "Partial Scholarship"),
                        ],
                        max_length=20,
                        verbose_name="Funding",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "fields",
                    models.JSONField(default=list, verbose_name="Fields of Study"),
                ),
                (
                    "stipend",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Stipend"
                    ),
                ),
                ("benefits", models.TextField(blank=True, verbose_name="Benefits")),
                ("deadline", models.DateField(verbose_name="Deadline")),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Start Date"),
                ),
                (
                    "requirements",
                    models.TextField(blank=True, verbose_name="Requirements"),
                ),
                (
                    "min_gpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="Minimum GPA",
                    ),
                ),
                (
                    "language_requirements",
                    models.TextField(blank=True, verbose_name="Language Requirements"),
                ),
                (
                    "application_url",
                    models.URLField(blank=True, verbose_name="Application URL"),
                ),
                (
                    "application_fee",
                    models.BooleanField(default=False, verbose_name="Application Fee"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Featured"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="scholarships/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Scholarship",
                "verbose_name_plural": "Scholarships",
                "ordering": ["-deadline", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-deadline"], name="scholarship_deadlin_80acca_idx"
                    ),
                    models.Index(
                        fields=["is_active", "-created_at"],
                        name="scholarship_is_acti_186421_idx",
                    ),
                ],
            },
        ),
    ]
