# Generated by Django 4.2.30 on 2026-05-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarship",
            name="faqs",
            field=models.JSONField(blank=True, default=list, verbose_name="FAQs"),
        ),
    ]
