# Generated by Django 4.2.30 on 2026-05-07 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0002_scholarship_faqs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scholarship",
            name="faqs",
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("application", "Application"),
                            ("requirements", "Requirements"),
                            ("financial", "Financial"),
                            ("visa", "Visa"),
                            ("accommodation", "Accommodation"),
                            ("other", "Other"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                ("question", models.CharField(max_length=500, verbose_name="Question")),
                ("answer", models.TextField(verbose_name="Answer")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "scholarship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="scholarships.scholarship",
                        verbose_name="Scholarship",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["order", "id"],
                "indexes": [
                    models.Index(
                        fields=["scholarship", "is_active"],
                        name="scholarship_scholar_69d113_idx",
                    )
                ],
            },
        ),
    ]
