# Generated by Django 6.0.5 on 2026-05-07 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="Title (English)"),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("cv", "CV/Resume"),
                            ("cover_letter", "Cover Letter"),
                            ("full_application", "Full Application"),
                            ("translation", "Translation"),
                            ("consultation", "Consultation"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Type",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="ILS", max_length=3, verbose_name="Currency"
                    ),
                ),
                ("features", models.JSONField(default=list, verbose_name="Features")),
                (
                    "delivery_time",
                    models.CharField(max_length=50, verbose_name="Delivery Time"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_popular",
                    models.BooleanField(default=False, verbose_name="Popular"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="Icon"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="ServiceOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("paid", "Paid"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "payment_method",
                    models.CharField(
                        default="palpay", max_length=20, verbose_name="Payment Method"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Transaction ID"
                    ),
                ),
                (
                    "payment_receipt",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="payments/",
                        verbose_name="Payment Receipt",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Paid Amount"
                    ),
                ),
                (
                    "delivered_files",
                    models.JSONField(default=list, verbose_name="Delivered Files"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Delivered At"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="services.service",
                        verbose_name="Service",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Order",
                "verbose_name_plural": "Service Orders",
                "ordering": ["-created_at"],
            },
        ),
    ]
