# Generated by Django 4.2.30 on 2026-06-04 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_serviceorder_customer_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoverLetterServiceOrder",
            fields=[],
            options={
                "verbose_name": "طلب رسالة التحفيز",
                "verbose_name_plural": "طلبات رسالة التحفيز",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("services.serviceorder",),
        ),
        migrations.CreateModel(
            name="CVServiceOrder",
            fields=[],
            options={
                "verbose_name": "طلب السيرة الذاتية",
                "verbose_name_plural": "طلبات السيرة الذاتية",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("services.serviceorder",),
        ),
    ]
