# Generated by Django 4.2.30 on 2026-06-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_contactsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactsettings",
            name="email",
            field=models.EmailField(
                default="info@amdist.ps", max_length=254, verbose_name="Email"
            ),
        ),
    ]
