# Generated by Django 6.0.5 on 2026-05-07 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scholarships", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "cover_letter",
                    models.TextField(blank=True, verbose_name="Cover Letter"),
                ),
                (
                    "personal_statement",
                    models.TextField(blank=True, verbose_name="Personal Statement"),
                ),
                (
                    "cv",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="applications/cv/",
                        verbose_name="CV",
                    ),
                ),
                (
                    "transcripts",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="applications/transcripts/",
                        verbose_name="Transcripts",
                    ),
                ),
                (
                    "recommendation_letters",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="applications/recommendations/",
                        verbose_name="Recommendation Letters",
                    ),
                ),
                (
                    "other_documents",
                    models.JSONField(default=list, verbose_name="Other Documents"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Submitted At"
                    ),
                ),
                (
                    "external_application_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="External Application ID",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Admin Notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "scholarship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="scholarships.scholarship",
                        verbose_name="Scholarship",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
                "ordering": ["-created_at"],
                "unique_together": {("user", "scholarship")},
            },
        ),
    ]
