# Generated by Django 4.2.30 on 2026-05-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="additional_comments",
            field=models.TextField(blank=True, verbose_name="Additional Comments"),
        ),
        migrations.AddField(
            model_name="application",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Date of Birth"),
        ),
        migrations.AddField(
            model_name="application",
            name="education_level",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Education Level"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="application",
            name="field_of_study",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Field of Study"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Full Name"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="gender",
            field=models.CharField(blank=True, max_length=10, verbose_name="Gender"),
        ),
        migrations.AddField(
            model_name="application",
            name="gpa",
            field=models.CharField(blank=True, max_length=20, verbose_name="GPA"),
        ),
        migrations.AddField(
            model_name="application",
            name="graduation_year",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Graduation Year"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="nationality",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Nationality"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="payment_receipt",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="applications/payment/",
                verbose_name="Payment Receipt",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Phone"),
        ),
        migrations.AddField(
            model_name="application",
            name="university",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="University"
            ),
        ),
    ]
