# Generated by Django 4.2.30 on 2026-06-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_alter_application_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="work_experience",
            field=models.TextField(blank=True, verbose_name="Work Experience"),
        ),
    ]
