# Generated by Django 4.2.30 on 2026-06-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0005_application_work_experience"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="cv",
        ),
        migrations.AddField(
            model_name="application",
            name="palestinian_id",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="applications/palestinian_id/",
                verbose_name="Palestinian ID",
            ),
        ),
    ]
